---
- hosts: all 
  
  become: yes

  tasks:
    - name: Install Apache2 web server
      yum:
        name: httpd
        state: present

    - name: Ensure that Apache is up and running and will autostart on system boot
      service:
        name: httpd
        state: started
        enabled: true
    
