---
# tasks file for codedeploy
- name: Download the installer package
  get_url:
    url: https://s3.amazonaws.com/aws-codedeploy-us-east-1/latest/install
    dest: /tmp/codedeploy-agent-install
    mode: 755

- name: Install CodeDeploy agent
  command: /tmp/codedeploy-agent-install auto

- name: Start the service and ensure that it is running on system boot
  service:
    name: codedeploy-agent
    state: started
    enabled: yes